### ISSUE TITLE
Wrong message when finishing a feature

### ISSUE THREAD

**Issue by leompeters** [OpherV/gitflow4idea#144]
I am getting the message below on Event Log:

```
5:20 PM	XXX-15: The feature branch 'feature/XXX-15' was merged into 'null'
```

When finished I am into `develop`.

In my `./.git/config` I have:

```
...
[gitflow "branch"]
	master = master
	develop = develop
[gitflow "prefix"]
	feature = feature/
	release = release/
	hotfix = hotfix/
	support = support/
	versiontag = v
```

> _Similar: #129 - Wrong message when finishing a feature_

**Comment by leomperes** [comment]
#129

**Comment by OpherV** [comment]
That is strange. What branch was `feature/xxx-15` based on?
Perhaps a branch that got deleted?

**Comment by leomperes** [comment]
Hi @OpherV, yes that is any branch I had finished by git-flow. The right message should be `... was merged into 'develop'`.

I am afraid getting that because on line 205 of `./src/gitflow/GitflowConfigUtil.java` you are setting the `baseBranch = null` on commit https://github.com/OpherV/gitflow4idea/commit/3057ce861403cd75cd69714ef449c8d0675a49ec

**Comment by OpherV** [comment]
Fixed in 0.6.1

**Comment by sacerro** [comment]
Hi,
Have the same issue.

I can't give you specific details about how to reproduce the issue..

Steps I did: 
I made a new Feature -> Gitflow -> Start Feature
I made my changes, commits and more
I publish feature -> Gitflow -> Publish Feature
Other developers made his changes, I pull changes, everything is Ok and again I made my changes
I finish feature -> Gitflow -> Finish Feature

Suddenly Gitflow notification saids: Feature X merged to 'null'. In online repo (Bitbucket), changes are not merged, branchs was deleted and commits too.


Details:

Win 10 (latest stable compilation)
IntelliJ Idea 2017.2.6
Git Flow Integration 0.6.3


Idea Log:

`
git -c core.quotepath=false -c log.showSignature=false flow feature finish screens 
2017-11-17 09:40:24,695 [ 162890]   INFO -  #git4idea.commands.GitHandler - Switched to branch 'develop' 
2017-11-17 09:40:28,478 [ 166673]   INFO -  #git4idea.commands.GitHandler - To bitbucket.org:companyname/projectname.git 
2017-11-17 09:40:28,478 [ 166673]   INFO -  #git4idea.commands.GitHandler - - [deleted]         feature/screens 
2017-11-17 09:40:28,881 [ 167076]   INFO -  #git4idea.commands.GitHandler - git flow took 13552 ms. Command parameters: 
"C:\Program Files\JetBrains\IntelliJ IDEA 2017.2.2\bin\runnerw.exe" "C:\Program Files\Git\bin\git.exe" -c core.quotepath=false -c log.showSignature=false flow feature finish screens 
2017-11-17 09:40:28,881 [ 167076]   INFO - notification.NotificationGroup - Notification group Gitflow Errors is already registered 
java.lang.Throwable
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:65)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:50)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:43)
	at gitflow.ui.NotifyUtil.<clinit>(NotifyUtil.java:13)
	at gitflow.actions.FinishFeatureAction$1.run(FinishFeatureAction.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:718)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-11-17 09:42:31,711 [ 289906]   INFO - g.FileBasedIndexProjectHandler - Reindexing refreshed files: 43 to update, calculated in 109ms 
2017-11-17 09:42:32,828 [ 291023]   INFO - son.PackageVersionRangeMatcher - Matching 36 done in 283 ms, not matched: [] 
2017-11-17 09:42:32,984 [ 291179]   INFO - .diagnostic.PerformanceWatcher - Reindexing refreshed files took 1273ms; general responsiveness: ok; EDT responsiveness: ok 
2017-11-17 09:57:05,520 [1163715]   INFO - figurations.GeneralCommandLine - Executable is not specified 
com.intellij.execution.ExecutionException: Executable is not specified
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:376)
	at org.intellij.erlang.utils.ExtProcessUtil.execAndGetFirstLine(ExtProcessUtil.java:40)
	at org.intellij.erlang.settings.ErlangExternalToolsConfigurable.validateEmacsPath(ErlangExternalToolsConfigurable.java:168)
	at org.intellij.erlang.settings.ErlangExternalToolsConfigurable.reset(ErlangExternalToolsConfigurable.java:160)
	at org.intellij.erlang.settings.ErlangExternalToolsConfigurable.<init>(ErlangExternalToolsConfigurable.java:99)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:75)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:341)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:267)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.a(ConfigurableWrapper.java:58)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:117)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:98)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getId(ConfigurableWrapper.java:194)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.groupConfigurables(ConfigurableExtensionPointUtil.java:269)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:145)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:136)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:67)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:63)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:52)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:300)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:117)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:117)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
	at java.awt.Component.processMouseEvent(Component.java:6541)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6306)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4897)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4719)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by carnau** [comment]
Hello,

I'm still getting this error on MacOs, doesn't matter if I make a feature based on develop or any other feature, it always merge against 'null' which is develop. Really annoying as I can't finish a branch that was not based on develop, so I have to move and pull the changes and delete it manually.

Whatever I can provide to fix it, I will be happy to help.

**Comment by OpherV** [comment]
I finally figured out why this happens. Turns out that the reason is that because reading the gitflow config (where the info about the base branch is saved) is IO bound, by the time the message is displayed the feature was already closed and so there is no information in the config file about it.

**Comment by OpherV** [comment]
As it happens the solution was to flip two lines. Seriously. 
Some bugs are like that - long time to debug, no time to resolve.
Fix in 0.7.0, once that's out
